package lucee.runtime.ai;

/**
 * The Response interface defines methods for accessing the results of an AI service inquiry.
 * 
 * This interface provides access to the textual response from the AI and metadata about the
 * computational resources consumed during processing.
 */
public interface Response {

	/**
	 * Returns the textual answer generated by the AI service.
	 * 
	 * This method retrieves the complete response text returned by the AI model in response to the
	 * user's inquiry.
	 *
	 * @return String containing the AI-generated answer
	 */
	public String getAnswer();

	/**
	 * Returns the total number of tokens used in processing this response.
	 * 
	 * Tokens are the basic units of text processing for many AI models, roughly corresponding to word
	 * fragments. This count typically includes tokens from both the input message and the generated
	 * response, and may be used for monitoring resource usage or billing purposes.
	 *
	 * @return long value representing the total token count consumed
	 */
	public long getTotalTokenUsed();
}