name: Migrate OSSRH Snapshots

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run OSSRH Snapshots Migration
      run: |
        chmod +x ./.github/scripts/migrate-old-snapshots.sh
        ./.github/scripts/migrate-old-snapshots.sh