name: Run OSV Scanner 

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build Lucee without using a Maven cache
      run: ant -noinput -buildfile loader/build.xml fast
    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '>=1.21.6'
    - name: Install Google OSV Scanner
      run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1.8.1
    - name: Run OSV vulnerabilities Scanner
      run: 'PATH="${PATH}:$(go env GOPATH)/bin" osv-scanner -r ${{ github.workspace }}'
