# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Update Provider

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      luceeVersion: zero-7.0.0.169-SNAPSHOT

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: lucee-script-runner-maven-cache
    - name: Trigger Lucee Update Providers
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/test
        execute: /update-provider.cfm
        luceeVersion: ${{ env.luceeVersion }}
        extensions:
        extensionDir:
